<?php
// create_storage_link.php
// Upload this file to public_html and open it once in the browser.
// After success - delete this file for security.

// CONFIG: adjust if your storage path differs
$target = '/home/universa/ushbd-app/storage/app/public'; // real storage (Laravel default)
$link   = __DIR__ . '/storage'; // will be public_html/storage

header('Content-Type: text/plain; charset=utf-8');

echo "Attempting to link:\n";
echo "  target: $target\n";
echo "  link:   $link\n\n";

if (!file_exists($target)) {
    echo "ERROR: target path does not exist: $target\n";
    exit(1);
}

// if a link/file already exists at link location
if (is_link($link)) {
    $real = readlink($link);
    echo "Notice: $link already exists as symlink -> $real\n";
    if ($real === $target) {
        echo "Already correct. Nothing to do.\n";
        exit(0);
    } else {
        echo "You may remove the existing symlink if you want to recreate it.\n";
        exit(1);
    }
}
if (file_exists($link)) {
    echo "ERROR: A file or directory already exists at $link.\n";
    echo "Please remove or rename it and re-run this script.\n";
    exit(1);
}

// Try to create a symlink
$ok = false;
if (function_exists('symlink')) {
    // suppress warnings and check return value
    $res = @symlink($target, $link);
    if ($res === true) {
        echo "Success: Created symlink $link -> $target\n";
        $ok = true;
        // try to set permissions (best-effort)
        @chmod($link, 0755);
    } else {
        echo "Warning: symlink() failed or is disabled.\n";
    }
} else {
    echo "Notice: symlink() is not available in this PHP build.\n";
}

// Fallback: try exec ln -s (may be disabled)
if (!$ok && function_exists('exec')) {
    @exec("ln -s " . escapeshellarg($target) . " " . escapeshellarg($link) . " 2>&1", $out, $ret);
    if ($ret === 0 && is_link($link)) {
        echo "Success: created symlink via exec ln -s\n";
        $ok = true;
    } else {
        echo "Notice: exec('ln -s') failed or disabled. Output:\n";
        echo implode("\n", $out) . "\n";
    }
}

if ($ok) {
    echo "\nDone. public storage should be available at /storage\n";
    echo "Important: Remove this script from your server now for security.\n";
    exit(0);
}

// If we reached here, symlink not possible. Create a safe proxy as fallback.
echo "\nFALLBACK: Creating PHP proxy and .htaccess to serve files from storage.\n";

$storageDir = $link; // public_html/storage (we will create a directory)
$serveFile = $storageDir . '/_serve.php';
$htaccessFile = __DIR__ . '/.htaccess';

// make storage directory
if (!mkdir($storageDir, 0755, true)) {
    echo "ERROR: Failed to create directory $storageDir. Check permissions.\n";
    exit(1);
}
echo "Created directory $storageDir\n";

// write _serve.php
$servePhp = <<<'PHP'
<?php
// _serve.php - serves files from the real storage directory.
// This file is auto-created by create_storage_link.php
// SECURITY: prevents path traversal and only serves existing files.

$real_base = '/home/universa/ushbd-app/storage/app/public'; // <-- keep in sync with create script
if (!is_dir($real_base)) {
    http_response_code(404);
    echo "Storage base not found.";
    exit;
}

$requested = isset($_GET['f']) ? $_GET['f'] : '';
$requested = trim($requested, "/\\\0");

// prevent traversal
if (strpos($requested, '..') !== false) {
    http_response_code(400);
    echo "Bad request.";
    exit;
}

$path = $real_base . '/' . $requested;
if (!is_file($path) || !is_readable($path)) {
    http_response_code(404);
    echo "File not found.";
    exit;
}

// send proper headers
$size = filesize($path);
$finfo = finfo_open(FILEINFO_MIME_TYPE);
$mime = finfo_file($finfo, $path) ?: 'application/octet-stream';
finfo_close($finfo);

header('Content-Type: ' . $mime);
header('Content-Length: ' . $size);
header('Cache-Control: public, max-age=3600');

// For images / inline types you may omit attachment
$basename = basename($path);
$disposition = 'inline';
header('Content-Disposition: ' . $disposition . '; filename="' . $basename . '"');

// read file in chunks
$fp = fopen($path, 'rb');
if ($fp) {
    while (!feof($fp)) {
        echo fread($fp, 8192);
        flush();
    }
    fclose($fp);
}
exit;
PHP;

if (file_put_contents($serveFile, $servePhp) === false) {
    echo "ERROR: Failed to write $serveFile\n";
    exit(1);
}
@chmod($serveFile, 0644);
echo "Wrote proxy: $serveFile\n";

// write .htaccess to rewrite /storage/<file> to storage/_serve.php?f=<file>
$ht = <<<'HT'
# Auto-generated by create_storage_link.php
RewriteEngine On
RewriteRule ^storage/(.*)$ /storage/_serve.php?f=$1 [L,QSA]
HT;

if (file_put_contents($htaccessFile, $ht) === false) {
    echo "ERROR: Failed to write .htaccess at $htaccessFile\n";
    echo "You will need to add a rewrite rule manually:\n";
    echo "RewriteRule ^storage/(.*)$ /storage/_serve.php?f=$1 [L,QSA]\n";
    exit(1);
}
echo "Wrote .htaccess with rewrite rule.\n";

echo "\nFALLBACK ready. Now try accessing a file like:\n";
echo "  /storage/path/to/file.jpg  (this will be rewritten to storage/_serve.php)\n";
echo "\nIMPORTANT: After verifying everything works, delete create_storage_link.php and keep an eye on permissions.\n";

exit(0);
